### ISSUE TITLE
Missing function on context

### ISSUE THREAD

**Issue by ptomasroos** [yahoo/flux-router-component#18]
https://github.com/yahoo/flux-router-component/blob/master/actions/navigate.js#L21

Where is context.getAction coming from? 
It feels this is written for something that no one else can see a use-case for, not even in the example app where most of the context magic comes from lib/Context.js

**Comment by cesarandreu** [comment]
Sorta related, any thoughts on having an action plugin that lets you register a bunch of actions by name and then invoking them with just the name? It looks like that's the original intent for this issue, but since it's not in fluxible I'm wondering if you guys might've moved away from using this approach. If you did chose to move away from doing this, can you share some of the reasons why?
